# Default values for stunner.

#To set the namespace for the deployment use the --namespace=<your-namespace> --create-namespace
#additional commands when installing your release
#It will create the desired namespace if not present

stunner:
  deployment:
    name: stunner
    label: 
      app: stunner
    replica: 1
    container:
      name: stunnerd
      image:
        repository: ""
        name: l7mp/stunnerd
        pullPolicy: Always
        tag: 0.10.10
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 128Mi

      netdebug: 
        enabled: true


  service:
    port: 3478
  
  networkPolicy: enable
  
  standalone:
    enabled: false
    serviceAccountName: post-install-sa
    image:
      repository: ""
      name: l7mp/stunner-job
      pullPolicy: Always
      tag: latest
    config:
    #PLEASE CUSTOMIZE THE VALUES BELOW 
      STUNNER_REALM: stunner.l7mp.io
      STUNNER_PORT: 3478
      STUNNER_USERNAME: user
      STUNNER_PASSWORD: pass
      STUNNER_LOGLEVEL: all:WARN
      STUNNER_MIN_PORT: 10000
      STUNNER_MAX_PORT: 20000
